### ISSUE TITLE
sw build failed

### ISSUE THREAD

**Issue by cissusnar** [egorpugin/primitives#1]
`
H:\Working\tesseract>sw build pub.egorpugin.primitives.command
[42/140] [pub.egorpugin.primitives.command-0.3.1]/src/command.cpp
Exception in file D:/dev/cppan2/client2/src/sw/builder/command.cpp:840, function execute1: When executing: [pub.egorpugin.primitives.command-0.3.1]/src/command.cpp
E:/Users/userA/.sw/storage/pkg/9d/a6/8d0d/src/sdir/src/command/src/command.cpp(142): error C2039: "contains":  "std::basic_string<char,std::char_traits<char>,std::allocator<char>>" ĳԱ
C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.29.30133\include\xstring(4871): note: μstd::basic_string<char,std::char_traits<char>,std::allocator<char>>
E:/Users/userA/.sw/storage/pkg/9d/a6/8d0d/src/sdir/src/command/src/command.cpp(147): note: 鿴ڱĺ ģ ʵauto primitives::Command::setProgram::<lambda_1>::()::<lambda_1>::operator ()<const char(&)[6]>(_T1) const
        with
        [
            _T1=const char (&)[6]
        ]
E:/Users/userA/.sw/storage/pkg/9d/a6/8d0d/src/sdir/src/command/src/command.cpp(147): error C3487: bool: зرʽƵΪͬ: ǰΪvoid
E:/Users/userA/.sw/storage/pkg/9d/a6/8d0d/src/sdir/src/command/src/command.cpp(144): error C3487: bool: зرʽƵΪͬ: ǰΪvoid
E:/Users/userA/.sw/storage/pkg/9d/a6/8d0d/src/sdir/src/command/src/command.cpp(144): error C2562: primitives::Command::setProgram::<lambda_1>::()::<lambda_1>::operator ():voidֵ
E:/Users/userA/.sw/storage/pkg/9d/a6/8d0d/src/sdir/src/command/src/command.cpp(147): note: μprimitives::Command::setProgram::<lambda_1>::()::<lambda_1>::operator ()
E:/Users/userA/.sw/storage/pkg/9d/a6/8d0d/src/sdir/src/command/src/command.cpp(147): error C2296: ||: Ƿvoid
E:/Users/userA/.sw/storage/pkg/9d/a6/8d0d/src/sdir/src/command/src/command.cpp(147): error C2297: ||: ǷҲvoid
command failed: exit code = 2
Total errors: 1
`

**Comment by livezingy** [comment]
1. I get the same error when I compile the tesseract5.3.1 on VS1019&win11 with sw.
There are some reference for this issue:
https://github.com/tesseract-ocr/tesseract/issues/4050
https://github.com/SoftwareNetwork/sw/issues/115
According the link, we may use VS2022 or compile tesseract without sw.

2. I compile the tesseract5.3.1  X64 successfully with vcpkg, cmake and command prompt on win11 refer to [workflows/vcpkg.yml](https://github.com/tesseract-ocr/tesseract/blob/main/.github/workflows/vcpkg.yml)

- Install cmake and vcpkg, Let's suppose the path of vcpkg is: D:/vcpkg. Add vcpkg and cmake path to environment variable Path.

- Build and Install Leptonica and image libraries using vcpkg. The Leptonica and image libraries will be installed in  D:/vcpkg/installed/x64-windows.
`vcpkg install leptonica:x64-windows`

- Build and Install PkgConfig. the workflow doesn't contain this step. it will report errors when we compile tesseract if we don't have PkgConfig.
`vcpkg install pkgconf:x64-windows`

- Install libarchive. the workflow doesn't contain this step. it will report errors when we compile tesseract if we don't have archive. The latest version of vcpkg untill 2023/6/26 could not intall archive because of some bug. we could download the compiled x64 [[libarchive].](https://www.libarchive.org/) Then unzip it and copy the .h/.dll/.lib files to the corresponding folders in D:/vcpkg/installed/x64-windows.

- Get the source code of tesseract5.3.1. Unzip it and come to its path in command prompt, then run the following command.
-DSW_BUILD=OFF  --->close SW
-DBUILD_SHARED_LIBS=ON     --->generate dll.
```
cmake . -B build -DCMAKE_BUILD_TYPE=Release -DSW_BUILD=OFF -DOPENMP_BUILD=OFF -DBUILD_SHARED_LIBS=ON -DBUILD_TRAINING_TOOLS=OFF "-DCMAKE_TOOLCHAIN_FILE=D:/vcpkg/scripts/buildsystems/vcpkg.cmake"
cmake --build build --config Release --target install
```

**Comment by egorpugin** [comment]
Build should work here now and for tess.
Use the latest VS2022 if you want to try sw builds.
